# Site
title:              Ram Iyer
bio:                'Writer, PowerShell addict, typographer, self-acclaimed rationalist.'
description:        "The official homepage of Ram Iyer, a writer, PowerShell addict, typographer and a self-acclaimed rationalist."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_IN
url:                //ramiyer.me

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  input: GFM
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            ramiyer07
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            iamramiyer
facebook:           iamramiyer
github-url:         theramiyer
#stackoverflow:     123456/username   from a "//stackoverflow.com/users/123456/username" link
linkedin:           theramiyer
#xing:              username
instagram:          iamramiyer
#lastfm:            username
#tumblr:            username
#medium:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
youtube:            ramiyer
#youtube-channel:   username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
keybase:            ramiyer
#xmpp:              username@server.com
#hackernews:        username
anchor:             ramiyer
gravatar:           e4a66264af2731abb223100c0b7dd481

# Gems
plugins:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Collections
collections:
  blogs:
    output: true
  books:
    output: true

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
